import config from "./hardhat-fork-polygon.config"

import "./tasks/deployEmissionsController"
import "./tasks/deployIntegration"
import "./tasks/deployFeeders"
import "./tasks/deployPolygon"
import "./tasks/deploySavingsContract4626"
import "./tasks/deployUnwrapper"
import "./tasks/bridge"
import "./tasks/emissions"
import "./tasks/feeder"
import "./tasks/masset"
import "./tasks/mUSD"
import "./tasks/token"
import "./tasks/ops"
import "./tasks/rewards"
import "./tasks/save"
import "./tasks/SaveWrapper"

export default config
