import config from "./hardhat.config"

import "./tasks/deployEmissionsController"
import "./tasks/deployIntegration"
import "./tasks/deployRewards"
import "./tasks/deployMbtc"
import "./tasks/deployFeeders"
import "./tasks/deployMV3"
import "./tasks/deployPolygon"
import "./tasks/deployRevenueForwarder"
import "./tasks/deployBriber"
import "./tasks/deploySavingsManager"
import "./tasks/deploySavingsContract4626"
import "./tasks/deployUnwrapper"
import "./tasks/bridge"
import "./tasks/dials"
import "./tasks/emissions"
import "./tasks/feeder"
import "./tasks/masset"
import "./tasks/mBTC"
import "./tasks/mUSD"
import "./tasks/ops"
import "./tasks/poker"
import "./tasks/prepareAccountFork"
import "./tasks/rewards"
import "./tasks/save"
import "./tasks/SaveWrapper"
import "./tasks/stakingV1"
import "./tasks/stakingV2"
import "./tasks/token"
import "./tasks/vault"
import "./tasks/ens"
import "./tasks/ironBankMigration"
import "./tasks/deployFuse"
import "./tasks/flat"

export default config
