import config from "./hardhat.config"

import "./tasks/deployIntegration"
import "./tasks/deployRewards"
import "./tasks/deployMbtc"
import "./tasks/deployFeeders"
import "./tasks/deployMV3"
import "./tasks/deployPolygon"
import "./tasks/feeder"
import "./tasks/mBTC"
import "./tasks/mUSD"
import "./tasks/ops"
import "./tasks/poker"
import "./tasks/rewards"
import "./tasks/SaveWrapper"
import "./tasks/stakingV1"
import "./tasks/stakingV2"
import "./tasks/token"
import "./tasks/vault"
import "./tasks/weekly"
import "./tasks/ens"

export default config
