/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(
        name: "AragonGovernancePortal"
      ): TruffleContracts.AragonGovernancePortalContract;
      require(name: "AWG"): TruffleContracts.AWGContract;
      require(name: "BasicToken"): TruffleContracts.BasicTokenContract;
      require(name: "Context"): TruffleContracts.ContextContract;
      require(name: "DAI"): TruffleContracts.DAIContract;
      require(name: "DGX"): TruffleContracts.DGXContract;
      require(name: "EGD"): TruffleContracts.EGDContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERC20Burnable"): TruffleContracts.ERC20BurnableContract;
      require(name: "ERC20Detailed"): TruffleContracts.ERC20DetailedContract;
      require(name: "ERC20Mintable"): TruffleContracts.ERC20MintableContract;
      require(name: "ERC20Mock"): TruffleContracts.ERC20MockContract;
      require(name: "ForgeLib"): TruffleContracts.ForgeLibContract;
      require(name: "ForgeLibV2"): TruffleContracts.ForgeLibV2Contract;
      require(name: "ForgeRewards"): TruffleContracts.ForgeRewardsContract;
      require(
        name: "ForgeRewardsMUSD"
      ): TruffleContracts.ForgeRewardsMUSDContract;
      require(
        name: "GovernancePortal"
      ): TruffleContracts.GovernancePortalContract;
      require(
        name: "GovernancePortalMock"
      ): TruffleContracts.GovernancePortalMockContract;
      require(
        name: "GovernancePortalModule"
      ): TruffleContracts.GovernancePortalModuleContract;
      require(name: "GUSD"): TruffleContracts.GUSDContract;
      require(name: "IAragonVoting"): TruffleContracts.IAragonVotingContract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "IForgeLib"): TruffleContracts.IForgeLibContract;
      require(
        name: "IGovernancePortal"
      ): TruffleContracts.IGovernancePortalContract;
      require(name: "IManager"): TruffleContracts.IManagerContract;
      require(name: "IMasset"): TruffleContracts.IMassetContract;
      require(name: "IMassetFactory"): TruffleContracts.IMassetFactoryContract;
      require(
        name: "IMassetForgeRewards"
      ): TruffleContracts.IMassetForgeRewardsContract;
      require(name: "IModulePub"): TruffleContracts.IModulePubContract;
      require(name: "IModuleSub"): TruffleContracts.IModuleSubContract;
      require(name: "INexus"): TruffleContracts.INexusContract;
      require(name: "IOracleHub"): TruffleContracts.IOracleHubContract;
      require(
        name: "IRecollateraliser"
      ): TruffleContracts.IRecollateraliserContract;
      require(name: "ISystok"): TruffleContracts.ISystokContract;
      require(name: "Manager"): TruffleContracts.ManagerContract;
      require(name: "ManagerMock"): TruffleContracts.ManagerMockContract;
      require(name: "ManagerModule"): TruffleContracts.ManagerModuleContract;
      require(name: "ManagerPortal"): TruffleContracts.ManagerPortalContract;
      require(name: "ManagerState"): TruffleContracts.ManagerStateContract;
      require(name: "Masset"): TruffleContracts.MassetContract;
      require(name: "MassetBasket"): TruffleContracts.MassetBasketContract;
      require(name: "MassetCore"): TruffleContracts.MassetCoreContract;
      require(name: "MassetFactory"): TruffleContracts.MassetFactoryContract;
      require(name: "MassetToken"): TruffleContracts.MassetTokenContract;
      require(name: "MetaToken"): TruffleContracts.MetaTokenContract;
      require(name: "MGLD"): TruffleContracts.MGLDContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "MinterRole"): TruffleContracts.MinterRoleContract;
      require(
        name: "MockERC20Factory"
      ): TruffleContracts.MockERC20FactoryContract;
      require(name: "MockPub"): TruffleContracts.MockPubContract;
      require(name: "ModuleA"): TruffleContracts.ModuleAContract;
      require(name: "ModuleB"): TruffleContracts.ModuleBContract;
      require(name: "ModuleC"): TruffleContracts.ModuleCContract;
      require(name: "ModuleKeys"): TruffleContracts.ModuleKeysContract;
      require(name: "ModulePub"): TruffleContracts.ModulePubContract;
      require(name: "ModuleSub"): TruffleContracts.ModuleSubContract;
      require(name: "MultiSigWallet"): TruffleContracts.MultiSigWalletContract;
      require(name: "MUSD"): TruffleContracts.MUSDContract;
      require(name: "Nexus"): TruffleContracts.NexusContract;
      require(name: "NexusMock"): TruffleContracts.NexusMockContract;
      require(name: "OGC"): TruffleContracts.OGCContract;
      require(name: "OracleHub"): TruffleContracts.OracleHubContract;
      require(name: "OracleHubData"): TruffleContracts.OracleHubDataContract;
      require(name: "OracleHubMock"): TruffleContracts.OracleHubMockContract;
      require(
        name: "OracleHubModule"
      ): TruffleContracts.OracleHubModuleContract;
      require(
        name: "OracleHubPriceData"
      ): TruffleContracts.OracleHubPriceDataContract;
      require(
        name: "OracleHubPriceDataMock"
      ): TruffleContracts.OracleHubPriceDataMockContract;
      require(name: "OracleHubView"): TruffleContracts.OracleHubViewContract;
      require(name: "PAX"): TruffleContracts.PAXContract;
      require(
        name: "Recollateraliser"
      ): TruffleContracts.RecollateraliserContract;
      require(
        name: "RecollateraliserModule"
      ): TruffleContracts.RecollateraliserModuleContract;
      require(
        name: "ReentrancyGuard"
      ): TruffleContracts.ReentrancyGuardContract;
      require(
        name: "SimpleOracleHub"
      ): TruffleContracts.SimpleOracleHubContract;
      require(
        name: "SimpleOracleHubMock"
      ): TruffleContracts.SimpleOracleHubMockContract;
      require(name: "SUSD"): TruffleContracts.SUSDContract;
      require(name: "Systok"): TruffleContracts.SystokContract;
      require(name: "SystokMock"): TruffleContracts.SystokMockContract;
      require(name: "TUSD"): TruffleContracts.TUSDContract;
      require(name: "USDC"): TruffleContracts.USDCContract;
      require(name: "USDT"): TruffleContracts.USDTContract;
    }
  }
}
